#!/usr/bin/env node
/*
 * Minimal MCP stdio server for the Volcano Claude Desktop extension.
 *
 * This is intentionally not the full Volcano MCP action surface. It provides
 * setup/instruction tools only, while the Volcano CLI remains the action path.
 */

const fs = require("node:fs");
const path = require("node:path");
const readline = require("node:readline");

const EXTENSION_ROOT = path.resolve(__dirname, "..");
const SKILLS_DIR = path.join(EXTENSION_ROOT, "skills");

function text(content) {
  return { content: [{ type: "text", text: content }] };
}

function cliInstallScript() {
  return "set -eu\n\nVOLCANO_WEB_URL=\"${VOLCANO_WEB_URL:-https://volcano.dev}\"\nVOLCANO_WEB_URL=\"${VOLCANO_WEB_URL%/}\"\n\nlog() { printf '%s\\n' \"volcano: $*\"; }\nwarn() { printf '%s\\n' \"volcano: $*\" >&2; }\nhave() { command -v \"$1\" >/dev/null 2>&1; }\n\ndownload() {\n  url=\"$1\"\n  dest=\"$2\"\n  if have curl; then\n    curl -fsSL \"$url\" -o \"$dest\"\n  elif have wget; then\n    wget -qO \"$dest\" \"$url\"\n  else\n    warn \"need curl or wget to download the Volcano CLI\"\n    return 1\n  fi\n}\n\nensure_cli_on_path() {\n  cli_dir=\"$1\"\n  case \":$PATH:\" in\n    *\":$cli_dir:\"*) ;;\n    *) PATH=\"$cli_dir:$PATH\"; export PATH ;;\n  esac\n\n  env_file=\"$HOME/.volcano/env\"\n  mkdir -p \"$(dirname \"$env_file\")\"\n  cat >\"$env_file\" <<ENV\n# Generated by Volcano plugin install-volcano. Adds the Volcano CLI install directory to PATH.\n# Source from your shell to make 'volcano' callable: . \"$env_file\"\ncase \":\\$PATH:\" in\n  *\":$cli_dir:\"*) ;;\n  *) export PATH=\"$cli_dir:\\$PATH\" ;;\nesac\nENV\n\n  marker_begin=\"# >>> volcano cli path >>>\"\n  marker_end=\"# <<< volcano cli path <<<\"\n  rc_added=\"\"\n  for rc in \"$HOME/.zshrc\" \"$HOME/.bashrc\" \"$HOME/.profile\"; do\n    [ -f \"$rc\" ] || continue\n    if grep -qF \"$marker_begin\" \"$rc\" 2>/dev/null; then\n      continue\n    fi\n    {\n      printf '\\n%s\\n' \"$marker_begin\"\n      printf '. \"%s\"\\n' \"$env_file\"\n      printf '%s\\n' \"$marker_end\"\n    } >>\"$rc\"\n    rc_added=\"$rc_added $rc\"\n  done\n  if [ -n \"$rc_added\" ]; then\n    log \"added Volcano PATH stub to:$rc_added\"\n  fi\n}\n\ninstall_cli_from_release() {\n  os=\"$(uname -s | tr '[:upper:]' '[:lower:]')\"\n  case \"$os\" in\n    linux*) os=\"linux\" ;;\n    darwin*) os=\"macos\" ;;\n    mingw*|msys*|cygwin*) os=\"windows\" ;;\n    *) warn \"unsupported OS '$os'; cannot install Volcano CLI\"; return 1 ;;\n  esac\n\n  arch=\"$(uname -m)\"\n  case \"$arch\" in\n    x86_64|amd64) arch=\"amd64\" ;;\n    arm64|aarch64) arch=\"arm64\" ;;\n    *) warn \"unsupported arch '$arch'; cannot install Volcano CLI\"; return 1 ;;\n  esac\n\n  ext=\"\"\n  [ \"$os\" = \"windows\" ] && ext=\".exe\"\n\n  case \"$VOLCANO_WEB_URL\" in\n    *localhost*|*127.0.0.1*)\n      url=\"https://github.com/Kong/volcano-cli/releases/download/nightly/volcano-${os}-${arch}${ext}\"\n      log \"local Volcano web origin detected; installing nightly CLI channel\"\n      ;;\n    *)\n      url=\"https://github.com/Kong/volcano-cli/releases/latest/download/volcano-${os}-${arch}${ext}\"\n      ;;\n  esac\n\n  dir=\"${VOLCANO_INSTALL_DIR:-}\"\n  if [ -z \"$dir\" ]; then\n    if [ -d /usr/local/bin ] && [ -w /usr/local/bin ]; then\n      dir=\"/usr/local/bin\"\n    else\n      dir=\"$HOME/.local/bin\"\n    fi\n  fi\n  mkdir -p \"$dir\"\n  out=\"$dir/volcano${ext}\"\n\n  log \"downloading Volcano CLI ($os-$arch) from $url\"\n  download \"$url\" \"$out\"\n  chmod 0755 \"$out\" 2>/dev/null || true\n  ensure_cli_on_path \"$dir\"\n  log \"installed Volcano CLI to $out\"\n}\n\nif have volcano; then\n  log \"found Volcano CLI at $(command -v volcano)\"\n  log \"upgrading Volcano CLI with: volcano upgrade\"\n  volcano upgrade\nelse\n  log \"Volcano CLI not found; installing latest release\"\n  install_cli_from_release\nfi\n\nif ! have volcano && [ -f \"$HOME/.volcano/env\" ]; then\n  . \"$HOME/.volcano/env\"\nfi\n\nif have volcano; then\n  log \"Volcano CLI ready: $(command -v volcano)\"\n  volcano --version || true\nelse\n  warn \"Volcano CLI installation did not leave 'volcano' on PATH. Try: . \\\"$HOME/.volcano/env\\\"\"\n  exit 1\nfi";
}

function setupInstructions() {
  const script = cliInstallScript();
  return [
    "# Install or upgrade Volcano for Claude Desktop",
    "",
    "Run this command in a terminal. It upgrades an existing volcano CLI with `volcano upgrade`, or downloads the latest CLI if missing.",
    "The Claude Desktop extension already ships Volcano skills, so this does not download skills into `~/.volcano/skills`.",
    "",
    "```sh",
    script,
    "```",
    "",
    "After it completes:",
    "",
    "1. Verify `which volcano` succeeds.",
    "2. Use the Volcano skills shipped with this Claude Desktop extension.",
    "",
    "Safety: production deploys, deletions, secret/variable changes, permission/visibility changes, custom domains, and billing/account changes require explicit user confirmation.",
  ].join("\n");
}


function readAgentInstructions() {
  const agents = path.join(SKILLS_DIR, "AGENTS.md");
  if (fs.existsSync(agents)) return fs.readFileSync(agents, "utf8");
  return `AGENTS.md is not present in ${SKILLS_DIR}. Reinstall the extension package or run install-volcano for CLI setup.`;
}

function skillIndex() {
  const indexPath = path.join(SKILLS_DIR, "index.json");
  if (fs.existsSync(indexPath)) return fs.readFileSync(indexPath, "utf8");

  if (!fs.existsSync(SKILLS_DIR)) {
    return `Skills directory not found: ${SKILLS_DIR}`;
  }

  const names = fs
    .readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .filter((entry) => fs.existsSync(path.join(SKILLS_DIR, entry.name, "SKILL.md")))
    .map((entry) => entry.name)
    .sort();

  return JSON.stringify({ skills: names }, null, 2);
}

const tools = [
  {
    name: "install-volcano",
    description: "Return the one-step Volcano CLI install/upgrade command for Claude Desktop.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "volcano_setup_instructions",
    description: "Return the canonical command for installing or upgrading the Volcano CLI.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "volcano_agent_instructions",
    description: "Return the canonical Volcano agent instructions from this extension's packaged skills directory.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "volcano_skill_index",
    description: "List the canonical Volcano skills included in this extension's packaged skills directory.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
];

function handleRequest(message) {
  const { id, method, params } = message;

  if (method === "initialize") {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        protocolVersion: params?.protocolVersion || "2024-11-05",
        capabilities: { tools: {} },
        serverInfo: { name: "volcano", version: "0.0.1" },
      },
    };
  }

  if (method === "tools/list") {
    return { jsonrpc: "2.0", id, result: { tools } };
  }

  if (method === "tools/call") {
    const name = params?.name;
    if (name === "install-volcano" || name === "volcano_setup_instructions") {
      return { jsonrpc: "2.0", id, result: text(setupInstructions()) };
    }
    if (name === "volcano_agent_instructions") {
      return { jsonrpc: "2.0", id, result: text(readAgentInstructions()) };
    }
    if (name === "volcano_skill_index") {
      return { jsonrpc: "2.0", id, result: text(skillIndex()) };
    }
    return {
      jsonrpc: "2.0",
      id,
      error: { code: -32602, message: `Unknown tool: ${name}` },
    };
  }

  // Notifications (e.g. initialized) have no id and require no response.
  if (id === undefined || id === null) return undefined;

  return {
    jsonrpc: "2.0",
    id,
    error: { code: -32601, message: `Method not found: ${method}` },
  };
}

const rl = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
rl.on("line", (line) => {
  if (!line.trim()) return;
  try {
    const message = JSON.parse(line);
    const response = handleRequest(message);
    if (response) process.stdout.write(`${JSON.stringify(response)}\n`);
  } catch (error) {
    process.stdout.write(
      `${JSON.stringify({
        jsonrpc: "2.0",
        id: null,
        error: { code: -32700, message: error instanceof Error ? error.message : String(error) },
      })}\n`,
    );
  }
});
